### ISSUE TITLE
Проблема с wifi.h

### ISSUE THREAD

**Issue by sapolio** [GyverLibs/WiFiConnector#1]
Максимально пустой проект. Написан только Serial.println.
Конфиг:
```
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	gyverlibs/GyverHTTP @ ^1.0.21
	gyverlibs/WiFiConnector @ ^1.0.4
```
Сразу ловлю
_In file included from .pio/libdeps/esp32dev/WiFiConnector/src/WiFiConnector.cpp:1:
.pio/libdeps/esp32dev/WiFiConnector/src/WiFiConnector.h:7:10: fatal error: WiFi.h: No such file or directory_

Что делаю не так?

**Comment by GyverLibs** [comment]
всё верно, так и должно быть. Нужно либо подключить библиотеку, либо убрать её из депсов
